### ISSUE TITLE
Lectura 8 ejercicio 1.2 

### ISSUE THREAD

**Issue by JorgeMartinez72** [gerdm/python_uma#15]
al momento de decir que en el constructor de la clase animales 
el valor `can_fly`  debe ser bolleano 
se refiere que se debe poner `True` o `False` dentro de los valores?
ejemplo.
```python
Tarantula = Animal("Aracnido", False)
```
o ese `False` debe ser sutituido por un "no puede volar" y 
al momento de ponerlo como atributo debe de arrojar False?

gracias

**Comment by gerdm** [comment]
Hola @JorgeMartinez72.

Justamente, hace referencia a poner `True` or `False` dentro del constructor.
