### ISSUE TITLE
ejercicio 2: inicialización de clases

### ISSUE THREAD

**Issue by JVilchis18** [gerdm/python_uma#17]
hola profesor cuando pongo mi código en la parte que necesito un booleano seria poner primero mi definición y después en la parte de si puede_volar sería: 
```python
self.puede_volar=True or False
```

**Comment by gerdm** [comment]
Hola @JVilchis18. Supongo estas hablando de definir la clase `Animal`

Considera que
```python
>>> True or False
True
```
Siempre será `True`. Lo que debes hacer es, dentro del constructor, hacer que el usuario asigne `True` o `False` al crear una nueva instancia de Animal. Por ejemplo

```python
>>> perro = Animal("perro", False)
```
En este caso
```python
>>> perro.puede_volar
False
```
