### ISSUE TITLE
Tarea: Essence of Linear Algebra

### ISSUE THREAD

**Issue by gerdm** [gerdm/python_uma#18]
Hola a todos,

Parte de la tarea para esta semana es ver y comentar los primeros tres episodios de *Essence of linear algebra* de 3Blue1Brown. Su tarea es hacer un comentario u aportación por cada uno de los tres episodios.

https://www.youtube.com/playlist?list=PLZHQObOWTQDPD3MizzM2xVFitgF8hE_ab

**Comment by michelorozco** [comment]
El primer vídeo me pareció interesante, lo que entendí es que los tipos de vectores son 3 y que los que usan vectores de tipo matemático lo que hacen es juntar la perspectiva del físico y la computista, y de esta forma poder hacer operaciones con los vectores, y que los vectores se representan en el plano como coordenadas y se pueden representar en distintas dimensiones.

**Comment by Lesly112504** [comment]
Del primer vídeo explica que hay 3 diferentes formas de analizar u observar un vector:
  1. El Físico ve al vector como una flecha.
  2. El Computista lo ve como una pareja de escalares
  3. El Matemático aplica tanto la visión del Físico y Computista
Se le puede aplicar dos operaciones a los vectores:
  Suma: Se suman los escalares (componente con componente)
  Multiplicación: Se multiplica componente con componente de dos vectores diferentes 
Hay vectores bidimensionales y tridimensionales.

**Comment by leonardo0529** [comment]
Primer vídeo
lo que entendí es que:
la base fundamental de  álgebra lineal es el vector, a el cual tiene  3 diferentes perspectivas como comento lesly, las operaciones importantes son la suma y multiplicación de vectores
cada par de numero tiene uno y solo un vector y cada vector esta asociado con uno y solo un par de números , si lo queremos hacer con tres dimensiones seria agarrando  el eje z y en ese caso serian 3.
Para poder sumar vectores tenemos que tomar el origen de un vector y moverlo hasta la punta del otro y colocar un nuevo vector donde termina el vector que se arrastra y esa sera la suma del vector 
los escalares son solo un mero y son los que nos ayudan  a hacer mas largo, corto o negativo a el vector

**Comment by AlexiaArroyo** [comment]
E1- Vectores 
Nos habla sobre la interpretación de los vectores; por ejemplo el físico observa una flecha con movimientos en el espacio, el Computista ve una unión de escalares en donde usa variables vistas para explicar sucesos y el matematico encuentra una unión en estas dos visiones jugando con ellas para generar nuevos datos. Este juego de datos se ve con la suma y multiplicacion de vectores, lo que genera nuevos vectores siendo en el caso de suma un reacomodo de los mismos y la multiplicacion una ampliación o una reducción de los mismos.

**Comment by leonardo0529** [comment]
Segundo Vídeo
Al principio del vídeo nos muestran la suma de los vectores  escalados que son cuando a dos vectores en vez de ponerle sus coordenadas x , y les asignas nombre, al poner a las coordenadas como escalares ya solo sumaríamos escalares.
los vectores tambien se pueden ver como puntos , si pensamos en una colección de vectores en una linea misma y si les quitamos las flechas solo quedarian puntos 
se dice que un vector es linealmente independiente si a este vector se le agrega otra dimensión respecto al espacio generado

**Comment by leonardo0529** [comment]
Tercer vídeo
Este vídeo habla de transformación lineal y su relación con las matrices,solo lo hace para dos dimensiones
la transformación lineal es básicamente una función cuando le metemos un valor a la función y nos regresa otro valor numérico y esto lo podemos pensar como un vector
hay diferentes tipos de transformaciones la mas sencilla es la que se le conoce como lineales , pose dos propiedades el origen debe mantenerse fijo al origen y debe mantener las lineas del plano, paralelas y equidistantes, y esta pueden rotar respecto al origen.
la propiedad de que se mantengan paralelas y equiristantes lleva a poder hacer comparaciones de vectores

**Comment by JuanPabloUMA18** [comment]
E1-
Nos da a entender que un vector es la parte fundamental del álgebra lineal, y que hay diferentes puntos de vista para analizarlo, son:
Física: define el vector como una flecha en un espacio bidimensional o tridimensional según sea el caso.
Computación: lo interpretan como una lista [] ordenando valores numéricos(escalares) como parejas dentro de la lista ordenada siempre en forma vertical y representando cada pareja un solo vector.
Matemáticas: utiliza ambas interpretaciones para definir que un vector puede ser cualquier cosa donde exista una noción de como sumarlo con otro vector o multiplicarlo con un numero.

**Comment by VictorMich** [comment]
Video 1:
Hay tres puntos de vista diferentes en las que se puede ver un vector, el matemático, físico y computacional. Los físicos lo toman como un lugar en el espacio, les importa su sentido, dirección y magnitud desde el plano R2 y R3. Para los científicos computacionales, lo toman como una lista de números en donde el orden sí importa, lo hace con 2 dimensiones. Los matemáticos lo toman como un vector que cumpla sus respectivos axiomas y engloba a las ciencias anteriores. 
En el álgebra lineal, el vector casi siempre se va colocar desde el origen y sus coordenadas serán los números dentro de la lista y te da las instrucciones de cómo se movió dentro del plano; en diferentes tipos de planos hay más números dentro de la lista, por lo anterior, más coordenadas. Su suma sólo funciona con otros vectores, la multiplicaión con escalares. 
Video 2:
Se pueden ver los vectores como en la forma i + j, que son la "base" de los escalares. Al sumar dos vectores se pueden obtener cualquier vector asociado con los escalares, cuando se suman se llama "combinación lineal". Si el vector está posicionado dentro de otro vector, sólo se podrán tener los mismos dentro de una línea, incluyendo al 0. Un vector se puede pensar como un punto en el plano y todas sus compinaciones posibles desde que empieza en cero pero pasa por el mismo punto del plano; como una línea recta. Su "span" son todas las combinaciones posibles de la suma de los vectores.
Video 3:
Nos explican de la tranformación lineal, en donde se conceptualizan todos los vectores como puntos en vez de usar todas sus colas o punto terminal. También nos dicen como la suma de dos vectores se puede ver como una transformación y nos introduce a la técnica para saber donde cae cada vector. Se pueden interpretar la caída del vector, en una matriz de 2x2 para saber a donde se llevará la transformación lineal a ese vector, es lo mismo que hacer la suma pero de una forma más general. Hay diferentes tipos de transformaciones, como "Shear". Las matrices se intepretan como la transformación de los espacios.

**Comment by JVilchis18** [comment]
1er vídeo:
Explica la manera de que se pueden ver los vectores, los cueles existen tres tipos: como ven los vectores los físicos, manera algebraica y por último como lo ven los programadores.
Como lo conocimos en física los vectores son aquellos que tienen magnitud, dirección y sentido.
En álgebra los vectores son  es una expresión geométrica que se extiende desde un punto de referencia llamado origen, hacia otro punto que se denomina extremo.
Y por ultimo los vectores computacionales son mejor conocidos como matrices los cuales almacenan bases de datos de un mismo tipo y representan imágenes  del  espacio geométrico.

2do vídeo:
Se utilizan dos tipos de vectores (vectores unitarios) los cuales el vector î nos indicara como es su movimiento son respecto al eje x  y el vector j se moverá con respecto al eje y los cuales siempre partirán del origen y al ser sumados darán como resultado un sistema de coordenadas. Si se desea la suma de estos vectores puede mover respecto a la punta del vector i o la punta del vector j o también se pueden mover por todo el espacio vectorial formando de esta manera un conjunto de vectores por todo este espacio en el plano 2D de otra forma en le plano 3D se imaginará un lámina en el espacio vectorial el cuál se moverá con la terminación de esta suma de vectores.
volviendo al tema del plano bidimensional cuando se tiene infinidad de vectores en el plano es mas fácil verlos como puntos que se ubicarán en la punta de estos.

3er vídeo:
Viéndolo desde el punto informático con su representación de imágenes vectoriales, el espacio vectorial se puede modificar se puede rotar pero nunca se puede mover del origen  o curvar sin embargo mientras las condiciones anteriores no sucedan no habrá problema, hablando de los vectores al cambiar su espacio cambiarán de coordenadas y su suma también lo hará para esto ya tendremos que hacer la suma de las coordenadas de los vectores cuando su espacio aun no se modificará y las nuevas coordenadas del espacio vectorial transformada para saber cuales serán las nuevas coordenadas de esta suma, y para concluir todas las transformaciones que se pueden hacer se le conoce como "Shear"

**Comment by paupauspau** [comment]
E1
Hay tres tipos de enfoque acerca de los vectores, la perspectiva del físico, la del computista y la del matemático.
-para el físico los vectores son flechas en el espacio y define al vector gracias a su longitud y a la dirección
-para el computista los vectores son listas ordenadas de números
-para el matemático es basarse en ambos enfoques, utilizando la suma de dos vectores o multiplicar un vector por un numero
Cuando se habla de dos dimensiones se tiene el eje x y el eje y, el sitio donde se intersectan se le llama origen, que es la raíz de todos los vectores. Cuando se habla de tres dimensiones lo que se agrega es un nuevo eje z perpendicular a los otros dos ejes.

E2
Habla sobre las coordenadas vectoriales que son los pares de números y vectores bidimensionales.
Cada coordenada es un escalar y se les llama vector “i” o vector unitario que va en dirección x y el que apunta hacia arriba es el vector “j”. Por lo que “i” y “j” son la base de un sistema de coordenadas.
Cada vez que se escalan dos vectores y se suman se le llama combinación lineal, ya que se fija un escalar y el otro cambia su valor.
También cada vector se le puede ver como puntos en el espacio.

E3
Habla sobre la transformación lineal y su relación con las matrices en dos dimensiones. El referirse a transformación es lo mismo que función, los cuales toman un vector y devuelven otro, quiere decir que cada punto en el espacio se mueve a otro punto.
Las transformaciones lineales también tienen dos propiedades:
-que todas las líneas no se pueden curvear, es decir que deben seguir siendo líneas
-deben mantener las líneas paralelas y equidistantes.

**Comment by noemiprian** [comment]
PRIMER VÍDEO:
En el primer vídeo podemos explicar que los vectores los manejan de tres diferentes maneras, como principio los físicos solo se enfocan en ver los vectores como flechas en el espacio y como definición lo especifican como su longitud y dirección en la que apuntan.
Las computista se enfocan mas numerariamente, como que los vectores son listas ordenada de números, es decir, distancias, etc. 
Comparando estas dos visiones el matemático contrae estas dos ideologías y generaliza diciendo que los vectores pueden ser cualquier cosa donde haya una noción de como sumar y multiplicar. Así mismo nos muestra como sumar los vectores con esta misma ideológica matemática y como multiplicar por un escalar. 
Fue un gran aporte de información, a pesar de que tenia un poco de conocimientos de como sumar vectores y multiplicarlos por una escalar, es un aporte extra bastante bien explicado. 
SEGUNDO VÍDEO:
Nos habla sobre dos vectores que son llamados la base de un sistema de coordenadas, es decir que las coordenadas las puedes ver como escalares y al sumarlos esto se asocia como una combinación lineal.
Nos menciona lo que es el espacio generado, refiriéndose al conjunto de vectores que puede alcanzar una combinación lineal de un par de vectores que se den. Si se piensa el espacio generado de manera tridimensional suele ser más complejo pensar en todas sus posibles combinaciones.
Este vídeo fue un poco más difícil de comprenderlo, pero sería bastante útil que se explicara de manera resumida en la clase. 
TERCER VÍDEO:
Este vídeo se enfoca más en la transformación lineal y su relación con las matrices, es decir en como se ven las transformaciones en el caso de dos dimensiones y como se relaciona la multiplicación de una matriz por un vector. Refiriéndose a tomar un vector de entrada y uno de salida llevándolo a todas las posibles combinaciones. 
Por lo tanto, las transformaciones lineales son todas aquellas que no hacen curvas a los vectores y el punto de origen nunca cambiara. Viéndolo de una manera numéricamente podríamos decir que tomando como base los puntos “i” y “j”, si aplicamos alguna transformación podríamos decir que de entrada tenemos la combinación lineal de “i” y “j” y de salida donde cae el vector que queremos y nos basamos en los puntos donde cae “i” y “j” eso nos da una transformación lineal.

**Comment by AlexiaArroyo** [comment]
E1- Vectores
Nos habla sobre la interpretación de los vectores; por ejemplo el físico observa una flecha con movimientos en el espacio, el computista ve una unión de escalares en donde usa variables vistas para explicar sucesos y el matemático encuentra una unión en estas dos visiones jugando con ellas para generar nuevos datos. Este juego de datos se ve con la suma y multiplicación de vectores, lo que genera nuevos vectores siendo en el caso de suma un nuevo acomodo de los mismos y la multiplicación una ampliación o una reducción de los mismos.

E2 - Combinación Lineal
En este segundo video se nos habla sobre una parte en especial del primer video, se nos introduce en lo que sucede en la suma y en la multiplicación de los vectores. Vemos como en la suma de vectores, movemos el resultado generado gráficamente generándonos lo que sería un plano, es decir, una recta vista en tres dimensiones. Así, de la misma forma se jugaría con los vectores bajo la influencia de la multiplicación, viendo como se expanden o contraen los vectores llegando a un tema de suma importancia, veríamos con estas operaciones fundamentales lo que una combinación lineal es. Lo anterior, se explica con la ecuación del plano, en donde los coeficientes que multiplican a las variables generan diferentes combinaciones lineales. 
Finalmente se analizó la dependencia e independencia lineal, la primera explicándose cuando un plano resulta ser la combinación lineal de la otra y la independencia resulta ser ajena a esta propiedad.

E3 - Transformaciones Lineales
Este video en especial, me pareció interesante el como se genera el movimiento al generar transformaciones lineales, tal ves nunca observamos el movimiento de los ejes cartesianos al aplicar este tema y el ver este movimiento me genero interés.
Las transformaciones lineales, como su nombre lo dice requiere de la permanencia de la linealidad al realizarse, busca no cambiar la estructura antes generada, es decir, la recta empleada así como la permanencia del origen en su estado original. 
Con lo anterior, se nos explica la esencia de las matrices, en donde una transformación lineal es el cambio de un vector de entrada, obteniendo un vector de salida, esto con la esencia de una multiplicación de matrices, renglón columna adicionando a multiplicación de un factor de cambio.

**Comment by MarianaRan** [comment]
Video 1. De acuerdo con el área de estudio, un vector puede ser definido de diferentes maneras. Para un programador, un vector es una manera de llamar a una lista; una lista numérica de aquellos aspectos que le interesa ordenar. 
Para comprender los vectores, es necesario pensarlos gráficamente. El vector es la unión del movimiento de los dos puntos que lo conforman. 

Video 2. Los vectores tienen dos elementos que lo componen: las escalas i y j. No se debe pensar en ellos como coordenadas, sino como elementos que "estiran" al vector. De acuerdo a su valor numérico es cuánto lo estiraron. La unión de estas dos escalas genera la combinación lineal. Y todas las posibilidades de valor que puede tomar esta combinación lineal puede tomar en el plano. 

Video 3. La transformación lineal se entiende como tener un vector inicial y terminar con un vector final. Se trata de incomes y outcomes. Para que sea una transformación lineal, el outcome debe seguir siendo lineal y debe haber un origen establecido. 
La matriz se entiende en dos partes: la parte a es donde "aterriza" la escala i; la parte b, la escala j.

**Comment by JorgeMartinez72** [comment]
Video 1:
No se me hizo raro el ver que hay 3 formas de ver a los vectores, del lado del físico (una flecha en el espacio), el lado del  computista (una lista ordenada de números) y el matemático (puede ser cualquier cosa que tenga la noción de poder ser sumado o multiplicado un vector)
lo que se me hace mas interesante, lo cual no lo había visto de esa manera, los vectores. Es que pueden aclarar  patrones de datos y dar una perspectiva global de lo que hacen ciertas operaciones, y poder describir el espacio y la manipulación de este, eso es lo que me impacto, la manipulación del espacio es algo que me tiene muy intrigado.

Video 2:
Es interesante como  es cierto que cuando en un sistema de vectores o el espacio  vectorial bidimensional   se ve afectado de una manera radical en la aplicación de un nuevo vector en eje z (3D) 
ya que el espacio vectorial,  que abarca la suma y multiplicación de ahora 3 vectores se vuelve mas "grande" y eso nos deja nuevas posibilidades

Video 3:
Es un poco confuso entender el vector por el cual se debe multiplicar la matriz de 2x2  ya que en la transformación me cuesta comprender en que se basa, entiendo que una transformacional lineal debe seguir los parámetros de que las lineas deben seguir rectas y equidistantes pero al rotar e intentar predecir  la transformación del vector resultante 
pero viendo de esa manera aun hay muchísimas formas de interpretar el espacio vectorial que podría abarcar el espacio de vectores, como se dijo al inicio, si manipulas un poco el espacio.

**Comment by SamuelCVz** [comment]
1er video.
Nos da las nociones básicas de los vectores, explica brevemente las interpretaciones de los vectores, en física, matemáticas y computación. En la parte computacional define al vector como un tipo de lista que tiene la forma de una matriz. Explica el concepto de escalar como un numero que multiplica al vector y lo escala, de ahí el nombre.

2do. video
Nos habla del concepto de base, y el span. nos define una medida de bases de una unidad en x (î) y en y(j), y el span, es el espacio generado de las posibles combinaciones lineales de dos vectores en el caso de un plano x, y o de tres vectores si se le agra un eje z. El pensar en las combinaciones en un plano xyz puede llegar a ser un poco más confusa ya que la representación tiende a tener un plano definido con dos de los vectores en lugar de una linea como en el caso de el plano en xy

3er video.
en este video se trata la transformación lineal y como se relaciona con la ms matrices en el plano xy, al decir transformacion podemos comprenderlo como una función ya que manipula a los vectores que se le asignan.

**Comment by LpavonPe** [comment]
Video 1:
En este video nos explica que hay tres diferentes perspectivas de los vectores, la física, la matemática y la computacional. Nos explica con sencillos ejemplos como son el escalamiento de vectores, así como la suma de estos principalmente desde una perspectiva física para después incursionar en una perspectiva matemática.

Video 2:
En este video nos habla sobre la base de los vectores, especialmente en R2 que son i, j y como todo vector se puede ver como una combinación lineal de su base, con este concepto en mente introduce el concepto de punto y recta desde una perspectiva de vectores para después ir a R3 donde también se puede ver todo vector como una combinación lineal pero ahora de la base de R3 que es i,j ,u para introducir también el concepto de planos.

Video 3:
En este video introduce el concepto de transformación de un espacio vectorial, pero lo restringe a transformaciones lineales donde nos explica cuáles son sus características, como se ve una transformación lineal de un espacio vectorial y cómo podemos expresarlo con matrices.

**Comment by abrilrm** [comment]
Video 1:
El primer video explica que hay tres perspectivas de ver a los vectores, una es la perspectiva de los físicos, otra es la perspectiva de los que estudian computación y la última es la perspectiva de los matemáticos. La manera que explica que es un vector desde la perspectiva de los físicos es que un vector es una flecha con dirección y magnitud en el espacio, los vectores en un plano son bidimensionales y los que están en el espacio son tridimensionales. Los vectores en la perspectiva de los que estudian computación es que los vectores son listas ordenadas de números. En la perspectiva de los matemáticos trata de englobar los dos puntos de vista diciendo que un vector es cualquier cosa en el plano que pueda sumarse y multiplicarse. 

Video 2:
En este video nos explica cómo podemos ver las coordenadas, que cada coordenada la pensemos como un escalar y que ese escalar se mueve por el plano bidimensional haciendo a esos escalares la base de los vectores. Se puede elegir cualquier vector, cualquier coordenada y mientras los movamos por el plano podemos obtener todos los vectores posibles que existen en un plano bidimensional. También podemos pensar en los vectores como puntos en el plano si están en diferentes direcciones y tienen diferente magnitud, los podemos ver como una simple línea cuan están en una línea aunque tengan diferente dirección pero el mismo ángulo.  

Video 3:
En el video tres explica las transformaciones de los vectores, dice que el álgebra lineal se enfoca en las trasformaciones lineales y que una transformación es un a función. Una transformación lineal es la que posee estas dos propiedades: todas las  líneas tienen que  mantenerse sin curvas y el origen tiene que estar siempre en el mismo sitio. Así que nos dice que las matrices son una transformación de un espacio, que es crucial saber que es una matriz para entender algebra lineal.

**Comment by michelorozco** [comment]
El segundo vídeo habla de las coordenadas como escalares que se pueden ver cómo dos vectores, estas coordenadas  se entienden como la suma de los vectores y a estos se les llama “sistema de coordenadas”. 
Si se fija un  escalar y se deja que el otro cambie su valor el vector traza una línea recta, si se deja que ambos vectores cambien se puede obtener una cantidad de puntos infinitos en el plano bidimensional, también se puede tener ambos vectores en la misma línea de puntos lo que hace que que estén limitados la cantidad de puntos que pueden alcanzar y hay una última posibilidad de que el vector esté en el origen, a todo esto se le llama “espacio generado”.
Una forma de pensar en los vectores es en forma de flechas pero cuando son conjuntos de vectores, muchas veces conviene pensar en ellos como puntos que generan líneas.

En el tercer vídeo se habla sobre las transformaciones son las que toman un vector y arrojan otro.
Las transformaciones lineales poseen dos propiedades: todas las líneas deben de ser rectas y el origen se debe de mantenerse fijo. 
La suma de vectores por lo que entendí se hace como suma de fracciones y luego lo que resulta de la suma la parte del numerador se multiplica por los puntos del primer vector y los otros se multiplican por el denominador de lo que resultó de la suma de fracciones y luego lo que resultó de las multiplicaciones se suma.
Las transformaciones lineales también se pueden entender como una forma de mover el espacio de tal manera que las cuadrículas sean paralelas y equidistantes y que mantengan su origen fijo
