### ISSUE TITLE
Tarea: Essence of linear algebra

### ISSUE THREAD

**Issue by elantonioguevara99** [gerdm/python_uma#22]
Episodio 1:
No da una introducción al Álgebra Lineal con uno de los conceptos más importantes que abarca el álgebra lineal como son los vectores.
Un vector es un conjunto ordenado de elementos (tupla) que tienen estas características en general
Magnitud: es la longitud, tamaño del segmento
Sentido: la orientación del segmento
Dirección: Es hacia a dónde va la flecha
Ya que en el vídeo también nos da otras 3 definiciones.
La de los físicos: Los vectores son flechas en el espacio dice que puedes mover el vector a cualquier lugar y seguirá siendo el mismo vector
La del computista: Es que los vectores son listas ordenadas de números en el contexto de los computistas "Vector" es una forma sofisticada de referirse a una "lista".
Los de los Matemáticos: Solo lo definen como cualquier cosa dónde haya una noción como sumar dos vectores o multiplicar un escalar por un vector.
La Geométrica: Se define como una flecha en el origen con las características propias antes mencionadas en un plano con coordenadas (x,y).
Un vector representa un movimiento.
Que la suma de dos vectores no la podemos imaginar cómo sí el primer vector se mueve a una distancia y dirección 1 y el segundo a una distancia y dirección 2 el efecto total es como si se hubiese movido a lo largo de la suma de los dos vectores primero. :)

**Comment by gerdm** [comment]
Hola @elantonioguevara99. Revisa #18 y comenta ahí, por favor.
