### ISSUE TITLE
Ejercicio 6 

### ISSUE THREAD

**Issue by JVilchis18** [gerdm/python_uma#23]
Hola @gerdm al poner mi programa

```python
[x in range(1,11) for x in range (1,11)]
```

Solo me sale una lista de true como le hago para que me multiplique x por el siguiente numero

**Comment by gerdm** [comment]
Hola @JVilchis18.

Considera el siguiente programa
```python
In [1]: x = 3                                                                                                     

In [2]: x in range(1, 11)                                                                                         
Out[2]: True
```

La primera parte de tu list comprehension sólo revisa si `x` se encuentra dentro de la rango `1, ..., 11`

**Comment by JVilchis18** [comment]
ya logre ver que mi x esta dentro del rango pero ahora no se como poner que se multiplique
