### ISSUE TITLE
Ejercicio 9

### ISSUE THREAD

**Issue by VictorMich** [gerdm/python_uma#24]
Buenas noches @gerdm , 

No entiendo bien como evaluar si un número es primo dentro de las dos listas de números que tenemos como subconjuntos para después poder evaluar si es True o False. Mi código es el siguiente:

`A={2,3,5,7,9}
B={1,3,7,15,31,63,127,255,511,1023}
def F(a,b): return 2**a - 1 == b
all([any([F(a,b) for a in A] for b in B)])`

Según yo me falta la parte de la evaluación de los primos, ya que el output de lo anterior es True cuando debería de ser False. ¿Algún tip? Gracias

**Comment by LpavonPe** [comment]
Hola @VictorMich en tu función no te ayudaría evaluar si los números, a y b son primos?, es decir:
`def F(a,b): return True if 2**a==b else False`
Para que ya después cheques si se cumple con tus conjuntos A y B con all y any.
Espero te sirva.
