### ISSUE TITLE
inclusión de Fuentes

### ISSUE THREAD

**Issue by LpavonPe** [gerdm/python_uma#26]
Hola @gerdm , estaba buscando algunas cosas para hacer en mi proyecto y me surgió la duda de si tenemos que incluir un archivo de texto con todas las fuentes (artículos, paginas, respuestas de Stackoverflow, etc.) que usemos para nuestro proyecto.

**Comment by gerdm** [comment]
Hola @LpavonPe. No, no es necesario hacer eso. Aunque sí es una buena idea que los guardes para referencias personales.
